import { readFileSync, readdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { renderSeoHead } from './structured-data.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const I18N_DIR = resolve(HERE, '../src/i18n')

/**
 * SEO footer link clusters, shared with the blog.
 *
 * Generated by scripts/build-footer-articles.mjs from the blog repo, so the
 * "which articles get promoted" decision lives in exactly one place
 * (aihavit-blog lib/footer-links.ts) instead of drifting between two sites.
 */
const FOOTER_ARTICLES = JSON.parse(
  readFileSync(resolve(I18N_DIR, 'footer-articles.json'), 'utf-8'),
)

/** Column headings per locale. Falls back to English for locales not listed. */
const FOOTER_GROUP_LABELS = {
  glp1Start: { en: 'STARTING GLP-1', ko: 'GLP-1 시작하기', ja: 'GLP-1 をはじめる', 'zh-tw': '開始使用 GLP-1', 'zh-cn': '开始使用 GLP-1', es: 'EMPEZAR CON GLP-1', de: 'GLP-1 STARTEN', fr: 'DÉBUTER LE GLP-1', pt: 'COMEÇAR COM GLP-1', it: 'INIZIARE CON GLP-1', id: 'MEMULAI GLP-1' },
  sideEffects: { en: 'SIDE EFFECT GUIDES', ko: '부작용 가이드', ja: '副作用ガイド', 'zh-tw': '副作用指南', 'zh-cn': '副作用指南', es: 'EFECTOS SECUNDARIOS', de: 'NEBENWIRKUNGEN', fr: 'EFFETS SECONDAIRES', pt: 'EFEITOS COLATERAIS', it: 'EFFETTI COLLATERALI', id: 'PANDUAN EFEK SAMPING' },
  compare: { en: 'COMPARE MEDICATIONS', ko: '약물 비교', ja: '薬の比較', 'zh-tw': '藥物比較', 'zh-cn': '药物比较', es: 'COMPARAR MEDICAMENTOS', de: 'MEDIKAMENTE VERGLEICHEN', fr: 'COMPARER LES TRAITEMENTS', pt: 'COMPARAR MEDICAMENTOS', it: 'CONFRONTA I FARMACI', id: 'BANDINGKAN OBAT' },
  interactions: { en: 'DRUG INTERACTIONS', ko: '병용·상호작용', ja: '併用・相互作用', 'zh-tw': '併用與交互作用', 'zh-cn': '联用与相互作用', es: 'INTERACCIONES', de: 'WECHSELWIRKUNGEN', fr: 'INTERACTIONS', pt: 'INTERAÇÕES', it: 'INTERAZIONI', id: 'INTERAKSI OBAT' },
  afterGlp1: { en: 'AFTER GLP-1', ko: '중단 후 유지', ja: '中止後の維持', 'zh-tw': '停藥後維持', 'zh-cn': '停药后维持', es: 'DESPUÉS DEL GLP-1', de: 'NACH GLP-1', fr: 'APRÈS LE GLP-1', pt: 'DEPOIS DO GLP-1', it: 'DOPO IL GLP-1', id: 'SETELAH GLP-1' },
  conditions: { en: 'FOR YOUR SITUATION', ko: '상황별 가이드', ja: '状況別ガイド', 'zh-tw': '依情況查看', 'zh-cn': '按情况查看', es: 'SEGÚN TU CASO', de: 'FÜR IHRE SITUATION', fr: 'SELON VOTRE CAS', pt: 'PARA O SEU CASO', it: 'IN BASE ALLA TUA SITUAZIONE', id: 'SESUAI KONDISI ANDA' },
}

const BLOG = 'https://blog.aihavit.com'

/**
 * Render the SEO cluster block for one locale.
 *
 * The blog only serves en/ko/ja/zh-tw (its other language paths return 410), so
 * every other homepage locale links into the English articles — pointing a
 * German visitor at /de/<slug> would send them to a 410.
 */
function renderFooterArticles(locale) {
  const blogLang = FOOTER_ARTICLES.blogLangs.includes(locale) ? locale : DEFAULT_LOCALE
  const cols = FOOTER_ARTICLES.groups
    .map((g) => {
      const heading =
        FOOTER_GROUP_LABELS[g.key]?.[locale] ?? FOOTER_GROUP_LABELS[g.key]?.[DEFAULT_LOCALE] ?? g.key
      const links = g.links
        .map((l) => {
          const label = l.labels[blogLang] ?? l.labels[DEFAULT_LOCALE]
          if (!label) return ''
          return `<a href="${BLOG}/${blogLang}/${l.slug}">${label}</a>`
        })
        .join('')
      return `<div class="footer__col"><p class="eyebrow">${heading}</p>${links}</div>`
    })
    .join('')
  return `<div class="footer__seo">${cols}</div>`
}

/**
 * Locales served by this site.
 *
 * SSOT is the app's own locale set (havit-wellness-app/app/assets/localization,
 * 35 ARB files). en_US is the root page and en_GB folds into it, leaving the 33
 * localized paths below.
 *
 * Note for SEO: the blog currently serves only en/ja/ko/zh-tw and 410s its other
 * language paths to concentrate crawl budget on a young domain. The homepage is
 * a single page rather than ~1k articles per language, so the thin-content risk
 * that drove that decision does not apply here in the same way — but if index
 * coverage stalls, this list is the lever to pull back.
 */
export const DEFAULT_LOCALE = 'en'

/** locale → { htmlLang, hreflang, native, dir } */
export const LOCALE_META = {
  en: { htmlLang: 'en', hreflang: 'en', native: 'English' },
  ar: { htmlLang: 'ar', hreflang: 'ar', native: 'العربية', dir: 'rtl' },
  ca: { htmlLang: 'ca', hreflang: 'ca', native: 'Català' },
  cs: { htmlLang: 'cs', hreflang: 'cs', native: 'Čeština' },
  da: { htmlLang: 'da', hreflang: 'da', native: 'Dansk' },
  de: { htmlLang: 'de', hreflang: 'de', native: 'Deutsch' },
  el: { htmlLang: 'el', hreflang: 'el', native: 'Ελληνικά' },
  es: { htmlLang: 'es', hreflang: 'es', native: 'Español' },
  fi: { htmlLang: 'fi', hreflang: 'fi', native: 'Suomi' },
  fr: { htmlLang: 'fr', hreflang: 'fr', native: 'Français' },
  he: { htmlLang: 'he', hreflang: 'he', native: 'עברית', dir: 'rtl' },
  hi: { htmlLang: 'hi', hreflang: 'hi', native: 'हिन्दी' },
  hr: { htmlLang: 'hr', hreflang: 'hr', native: 'Hrvatski' },
  hu: { htmlLang: 'hu', hreflang: 'hu', native: 'Magyar' },
  id: { htmlLang: 'id', hreflang: 'id', native: 'Bahasa Indonesia' },
  it: { htmlLang: 'it', hreflang: 'it', native: 'Italiano' },
  ja: { htmlLang: 'ja', hreflang: 'ja', native: '日本語' },
  ko: { htmlLang: 'ko', hreflang: 'ko', native: '한국어' },
  ms: { htmlLang: 'ms', hreflang: 'ms', native: 'Bahasa Melayu' },
  nb: { htmlLang: 'nb', hreflang: 'nb', native: 'Norsk bokmål' },
  nl: { htmlLang: 'nl', hreflang: 'nl', native: 'Nederlands' },
  pl: { htmlLang: 'pl', hreflang: 'pl', native: 'Polski' },
  pt: { htmlLang: 'pt', hreflang: 'pt', native: 'Português' },
  ro: { htmlLang: 'ro', hreflang: 'ro', native: 'Română' },
  ru: { htmlLang: 'ru', hreflang: 'ru', native: 'Русский' },
  sk: { htmlLang: 'sk', hreflang: 'sk', native: 'Slovenčina' },
  sv: { htmlLang: 'sv', hreflang: 'sv', native: 'Svenska' },
  th: { htmlLang: 'th', hreflang: 'th', native: 'ไทย' },
  tr: { htmlLang: 'tr', hreflang: 'tr', native: 'Türkçe' },
  uk: { htmlLang: 'uk', hreflang: 'uk', native: 'Українська' },
  uz: { htmlLang: 'uz', hreflang: 'uz', native: 'Oʻzbekcha' },
  vi: { htmlLang: 'vi', hreflang: 'vi', native: 'Tiếng Việt' },
  'zh-cn': { htmlLang: 'zh-Hans-CN', hreflang: 'zh-Hans', native: '简体中文' },
  'zh-tw': { htmlLang: 'zh-Hant-TW', hreflang: 'zh-Hant', native: '繁體中文' },
}

export const LOCALES = Object.keys(LOCALE_META)

const SITE = 'https://www.aihavit.com'

function loadDict(locale) {
  return JSON.parse(readFileSync(resolve(I18N_DIR, `${locale}.json`), 'utf-8'))
}

/**
 * Locales that actually have a translation file. LOCALE_META lists every locale
 * the site intends to serve; a locale without JSON is simply not emitted rather
 * than failing the build, so languages can land one at a time.
 */
export function translatedLocales() {
  const present = new Set(
    readdirSync(I18N_DIR).filter((f) => f.endsWith('.json')).map((f) => f.replace(/\.json$/, '')),
  )
  return LOCALES.filter((l) => l === DEFAULT_LOCALE || present.has(l))
}

/** Absolute site URL for a locale's home page. */
export function localeUrl(locale) {
  return locale === DEFAULT_LOCALE ? `${SITE}/` : `${SITE}/${locale}/`
}

/**
 * Swap every `data-i18n` element's inner HTML for the localized string.
 *
 * Values may contain inline markup (`<br>`, the underline `<span>`, the mailto
 * link), which is why this replaces innerHTML wholesale rather than text only —
 * translations carry their own markup. Only leaf elements are keyed (see the
 * instrumentation in index.html), so the non-greedy match cannot swallow a
 * nested element of the same tag.
 */
function translateBody(html, dict) {
  let missing = 0
  const out = html.replace(
    /<([a-z0-9]+)([^>]*\sdata-i18n="([^"]+)"[^>]*)>([\s\S]*?)<\/\1>/gi,
    (whole, tag, attrs, key, inner) => {
      const value = dict[key]
      if (value === undefined) {
        missing++
        return whole
      }
      return `<${tag}${attrs}>${value}</${tag}>`
    },
  )
  return { html: out, missing }
}

/**
 * Rewrite <html lang>, <title>, meta description, canonical + hreflang set, and
 * append the Open Graph / JSON-LD block.
 *
 * `baseHtml` is the untranslated index.html: the default locale keeps its
 * strings in the markup rather than a dictionary, so the schema builder needs
 * the original to resolve a key when `dict` is empty.
 */
function translateHead(html, locale, dict, baseHtml) {
  const meta = LOCALE_META[locale]
  // Arabic and Hebrew need dir="rtl"; every other locale must not carry a stale
  // dir attribute, so the whole <html …> tag is rewritten rather than patched.
  const dirAttr = meta.dir ? ` dir="${meta.dir}"` : ''
  html = html.replace(/<html\b[^>]*>/i, `<html lang="${meta.htmlLang}"${dirAttr}>`)

  if (dict.__title) {
    html = html.replace(/<title>[\s\S]*?<\/title>/i, `<title>${dict.__title}</title>`)
  }
  if (dict.__description) {
    html = html.replace(
      /<meta\s+name="description"\s+content="[^"]*"\s*\/?>/i,
      `<meta name="description" content="${dict.__description}" />`,
    )
  }

  // Strip any previously-injected block so re-runs stay idempotent.
  html = html.replace(/\s*<!-- i18n:alternates -->[\s\S]*?<!-- \/i18n:alternates -->/i, '')
  html = html.replace(/\s*<!-- i18n:seo -->[\s\S]*?<!-- \/i18n:seo -->/i, '')

  const links = [
    `    <link rel="canonical" href="${localeUrl(locale)}" />`,
    ...translatedLocales().map(
      (l) =>
        `    <link rel="alternate" hreflang="${LOCALE_META[l].hreflang}" href="${localeUrl(l)}" />`,
    ),
    `    <link rel="alternate" hreflang="x-default" href="${localeUrl(DEFAULT_LOCALE)}" />`,
  ].join('\n')

  // Whatever survived the rewrites above is what the page actually says, so the
  // social tags and the schema read those final values back rather than
  // re-deriving them from the dictionary and risking a mismatch.
  const title = plainText((/<title>([\s\S]*?)<\/title>/i.exec(html) || [, ''])[1])
  const description = (/<meta\s+name="description"\s+content="([^"]*)"/i.exec(html) || [, ''])[1]

  const seo = renderSeoHead({
    locale,
    dict,
    baseHtml,
    title,
    description,
    url: localeUrl(locale),
    localeMeta: meta,
  })

  return html.replace(
    /<\/head>/i,
    `    <!-- i18n:alternates -->\n${links}\n    <!-- /i18n:alternates -->\n` +
      `    <!-- i18n:seo -->\n${seo}\n    <!-- /i18n:seo -->\n  </head>`,
  )
}

/** Entity-decoded, tag-free text — a dictionary <title> may carry entities. */
function plainText(str) {
  return str
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/\s+/g, ' ')
    .trim()
}

/** Swap the placeholder in index.html for this locale's cluster block. */
function injectFooterArticles(html, locale) {
  return html.replace(
    /<!-- i18n:footer-articles -->[\s\S]*?<!-- \/i18n:footer-articles -->/i,
    `<!-- i18n:footer-articles -->${renderFooterArticles(locale)}<!-- /i18n:footer-articles -->`,
  )
}

/**
 * Build the language menu. index.html ships a placeholder list; with 34 locales
 * it has to be generated rather than hand-maintained, and generating it per page
 * lets the current locale be marked with aria-current.
 */
function renderLangMenu(html, locale) {
  const items = translatedLocales().map((l) => {
    const cur = l === locale ? ' aria-current="true"' : ''
    return `<a href="${l === DEFAULT_LOCALE ? '/' : `/${l}/`}"${cur}>${LOCALE_META[l].native}</a>`
  }).join('')
  return html.replace(
    /(<div class="lang-switch__menu">)[\s\S]*?(<\/div>)/i,
    `$1${items}$2`,
  )
}

/** Root-relative asset paths already work from /<locale>/, so nothing to rewrite. */
export function renderLocale(baseHtml, locale) {
  const dict = locale === DEFAULT_LOCALE ? {} : loadDict(locale)
  const { html, missing } = locale === DEFAULT_LOCALE
    ? { html: baseHtml, missing: 0 }
    : translateBody(baseHtml, dict)
  const withHead = renderLangMenu(translateHead(html, locale, dict, baseHtml), locale)
  return { html: injectFooterArticles(withHead, locale), missing }
}

export default function i18nHtml() {
  return {
    name: 'havit-i18n-html',
    enforce: 'post',

    /**
     * Dev: serve every locale from the same source index.html.
     *
     * The root goes through renderLocale too even though English needs no
     * dictionary — the hreflang set, the language menu and the footer link
     * clusters are all injected there, so skipping it would make the page you
     * review locally differ from the one that ships.
     */
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const path = (req.url || '').split('?')[0]
        const m = /^\/([a-z-]+)\/?$/.exec(path)
        const locale = path === '/' ? DEFAULT_LOCALE : m && m[1]
        if (!locale || !translatedLocales().includes(locale)) return next()
        try {
          const raw = readFileSync(resolve(HERE, '../index.html'), 'utf-8')
          const url = locale === DEFAULT_LOCALE ? '/' : `/${locale}/`
          const transformed = await server.transformIndexHtml(url, raw)
          const { html, missing } = renderLocale(transformed, locale)
          if (missing) server.config.logger.warn(`[i18n] ${locale}: ${missing} missing keys`)
          res.setHeader('Content-Type', 'text/html')
          res.end(html)
        } catch (e) {
          next(e)
        }
      })
    },

    /** Build: emit one extra HTML file per non-default locale. */
    generateBundle(_options, bundle) {
      const index = bundle['index.html']
      if (!index) return
      const base = typeof index.source === 'string' ? index.source : index.source.toString()

      // The default locale still needs canonical + hreflang injected.
      const root = renderLocale(base, DEFAULT_LOCALE)
      index.source = root.html

      for (const locale of translatedLocales()) {
        if (locale === DEFAULT_LOCALE) continue
        const { html, missing } = renderLocale(base, locale)
        if (missing) this.warn(`[i18n] ${locale}: ${missing} keys missing from src/i18n/${locale}.json`)
        this.emitFile({ type: 'asset', fileName: `${locale}/index.html`, source: html })
      }
    },
  }
}

/** Sanity helper for scripts: which locale JSON files exist. */
export function availableLocales() {
  return readdirSync(I18N_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
}
